### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by TotalVerb** [TotalVerb/SchemeSyntax.jl#1]
## Meta

- [x] Move SimpleJulia out of SExpressions.jl
- [x] Create SchemeSyntax.jl
- [ ] Register SchemeSyntax.jl

## R5RS

- [ ] Support a larger part of the R5RS standard, modified to be more Julian
- [x] Enhance the `define` keyword to accept constants also
- [x] Ensure that `define` returns nothing
- [x] Add `not`
- [x] Add `set!`
- [ ] Reclaim `=` for `==`

## Racket

- [x] Ensure that `nothing` is accessible from `(void)` in lisp
- [x] Add `when`
- [ ] Add `for/list`

## Julia

- [x] Add `(.field obj)` field access syntax

## Deprecations

- [x] Deprecate using `=` in favour of `set!`
- [ ] Remove `=`
- [x] Deprecate `.` for field access
- [ ] Remove `.`
- [ ] Deprecate using keywords to get arbitrary expression bodies
- [ ] Replace with a more general technique
